### ISSUE TITLE
App displays no feedback when generating story cards

### ISSUE THREAD

**Issue by vadimt** [BrickworkSoftware/sprintly_tools#1]
I ran the script and then just sat there waiting, wondering what it was doing. Some visible feedback of activity "Started" Dot progress bar, whatever, would really make that wait less stressful.

**Comment by saadiq** [comment]
Previous sprints didn't have the SEVENTY SIX tasks of this one.  Updated. https://github.com/BrickworkSoftware/scripts/commit/bf99e03d6cd4372223bc0e8882da0f89919f5dc5
